### ISSUE TITLE
Ресерч развертывания всех микросервисов в облаке

### ISSUE THREAD

**Issue by v-v-d** [v-v-d/billing#2]
**Что решить:**
Надо понять как развернуть все микросервисы кинотеатра в облаке

**Что сделать:**
Провести ресерч, изучить предложение яндекса, изучить взаимодействие облака с докером

**Ожидаемый результат:**
В комментах к задаче есть инструкция как развернуть все сервисы в облаке

**Comment by balyakin** [comment]
Получил доступ к облаку яндекса, можем стартовать там виртуальную машину.

Есть доступ в докерхаб с возможностью автоматически создавать имейдже при пуше в мастер ветку репозитория github.

как настроить автоматическое создание образов в докерхабе описано тут:
https://techytok.com/docker-build-from-github/

**Comment by balyakin** [comment]
использовать такие имейджы в докер-композе на сервере можно через параметр image

**Comment by v-v-d** [comment]
done
