### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [v-v-d/billing#52]
Приветствую! Вы все молодцы, очень хорошо постарались. Работа выполнена грамотно. У меня минимум замечаний.
1. [исправить] Было бы неплохо вынести [классы](https://github.com/v-v-d/billing/blob/1566ace7468096f4aa67e596ee35f0dff5e19268/src/app/services/payments.py#L18) с ошибками в отдельный модуль, чтобы отделить их от логики сервисов. По мере развития проекта могут появляться и другие классы исключений и чтобы было проще поддерживать и развивать проект, лучше чтобы исключения находились в одном месте, например в модуле exceptions.py. Тоже самое касается и [исключения](https://github.com/v-v-d/billing/blob/1566ace7468096f4aa67e596ee35f0dff5e19268/src/app/services/transactions.py#L6) из модуля transactions.py.
2. [исправить] Было бы неплохо собрать все описания [ошибок](https://github.com/v-v-d/billing/blob/1566ace7468096f4aa67e596ee35f0dff5e19268/src/app/api/internal/v1/users_films.py#L19) в одном месте, чтобы в случае чего их можно было оперативно поменять. Может измениться локализация или банально захочется внести правки в текст. Сейчас придется ходить по всему коду, чтобы внести правки, что понятно может отнять прилично времени.
3. [можно лучше] [Здесь](https://github.com/v-v-d/billing/blob/1566ace7468096f4aa67e596ee35f0dff5e19268/src/tests/functional/src/api/internal/v1/users_films/test_mark_as_watched.py#L19) лучше в качестве кода ответа указать объект статуса из модуля http:
    
    ```
    from http import HTTPStatus
    assert response.status_code == HTTPStatus.OK, response.text
    ```
    Так будет выглядеть более наглядно и еще мы избавляемся от хардкода.

**Comment by v-v-d** [comment]
Привет! Спасибо за комменты. Все пофиксили + попутно еще кое-что поправили
https://github.com/v-v-d/billing/commit/0d8a5147830bdab174bc186a78388610d05f6cb6

**Comment by BigDeepBlue** [comment]
Принято! Удачи на защите диплома :)
